name = "free-palestine"
compatibility_date = "2024-12-01"
pages_build_output_dir = "out"

[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]  
NODE_ENV = "preview"

# Environment variables will be set through Cloudflare dashboard
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# RESEND_API_KEY
# ADMIN_EMAIL