name = "free-palestine"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Assets binding for static files
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NODE_ENV = "production"

# R2 bucket binding for Next.js incremental cache
[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "free-palestine-cache"

# Environment variables will be set through Cloudflare dashboard or wrangler secrets
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# RESEND_API_KEY
# ADMIN_EMAIL